import { readFileSync } from 'node:fs'
import { slug } from 'github-slugger'
import { defineConfig, type DefaultTheme } from 'vitepress'

// Generated by site/scripts/sync-docs.mjs from the repository's Markdown.
const generated = <T>(name: string): T =>
  JSON.parse(readFileSync(new URL(`./generated/${name}`, import.meta.url), 'utf8'))

const sidebar = generated<DefaultTheme.SidebarItem[]>('sidebar.json')
const home = generated<{ version: string; repository: string; npm: string }>('home.json')

// GitHub Pages paths are case-sensitive; this must match the repository name.
const base = process.env.SITE_BASE ?? '/mcp-3D-printer-server/'
const siteUrl = `https://dmontgomery40.github.io${base}`
const description =
  'An MCP server that lets Claude, Codex, and other MCP clients check on, slice for, and print to OctoPrint, Klipper, Duet, Repetier, Bambu Lab, Prusa, and Creality 3D printers.'
// Regenerate with `npm run social-card` after changing the design or copy.
const socialImage = `${siteUrl}social-card.png`
const socialImageAlt =
  'mcp-3d-printer-server: Print from a conversation. A chat asks an agent to fit a MakerWorld phone case to an iPhone 17 Pro Max and print it, beside a slicer preview of the first layer.'

export default defineConfig({
  srcDir: 'content',
  outDir: 'dist',
  base,
  lang: 'en-US',
  title: 'mcp-3d-printer-server',
  description,
  cleanUrls: true,
  head: [
    ['link', { rel: 'icon', type: 'image/svg+xml', href: `${base}favicon.svg` }],
    ['meta', { name: 'theme-color', content: '#0c6f6a' }],
    ['meta', { property: 'og:type', content: 'website' }],
    ['meta', { property: 'og:site_name', content: 'mcp-3d-printer-server' }],
    ['meta', { property: 'og:image', content: socialImage }],
    ['meta', { property: 'og:image:type', content: 'image/png' }],
    ['meta', { property: 'og:image:width', content: '1200' }],
    ['meta', { property: 'og:image:height', content: '630' }],
    ['meta', { property: 'og:image:alt', content: socialImageAlt }],
    ['meta', { name: 'twitter:card', content: 'summary_large_image' }],
    ['meta', { name: 'twitter:image', content: socialImage }],
    ['meta', { name: 'twitter:image:alt', content: socialImageAlt }],
  ],
  // Per-page titles, descriptions, and canonical URLs for link previews.
  transformHead({ pageData, title, description: pageDescription }) {
    const route = pageData.relativePath.replace(/(^|\/)index\.md$/, '$1').replace(/\.md$/, '')
    const url = `${siteUrl}${route}`
    return [
      ['meta', { property: 'og:title', content: title }],
      ['meta', { property: 'og:description', content: pageDescription }],
      ['meta', { property: 'og:url', content: url }],
      ['meta', { name: 'twitter:title', content: title }],
      ['meta', { name: 'twitter:description', content: pageDescription }],
      ['link', { rel: 'canonical', href: url }],
    ]
  },
  sitemap: { hostname: siteUrl },
  markdown: {
    // Match GitHub's heading anchors so README deep links keep working here.
    anchor: { slugify: slug },
    languageAlias: { env: 'dotenv' },
  },
  themeConfig: {
    logo: { src: '/logo.svg', alt: '' },
    siteTitle: 'mcp-3d-printer-server',
    nav: [
      { text: 'Guide', link: '/guide/', activeMatch: '^/guide/' },
      { text: 'Reference', link: '/reference/printer-tools', activeMatch: '^/reference/' },
      { text: 'Changelog', link: '/project/changelog', activeMatch: '^/project/changelog' },
      {
        text: `v${home.version}`,
        items: [
          { text: 'npm package', link: home.npm },
          { text: 'Releases', link: `${home.repository}/releases` },
          { text: 'Contributors', link: '/project/contributors' },
          { text: 'Report an issue', link: `${home.repository}/issues` },
        ],
      },
    ],
    sidebar,
    outline: { level: [2, 3], label: 'On this page' },
    search: { provider: 'local' },
    socialLinks: [
      { icon: 'github', link: home.repository, ariaLabel: 'GitHub repository' },
      { icon: 'npm', link: home.npm, ariaLabel: 'npm package' },
    ],
    editLink: {
      // VitePress serializes this function to the browser, so it must be self-contained.
      pattern: ({ frontmatter }) =>
        `https://github.com/DMontgomery40/mcp-3D-printer-server/edit/main/${frontmatter.sourceFile ?? 'README.md'}`,
      text: 'Edit the source on GitHub',
    },
    docFooter: { prev: 'Previous', next: 'Next' },
    footer: {
      message:
        'Released under the GPL-2.0 license. An independent open-source project, not affiliated with any printer manufacturer or host software.',
      copyright: 'Copyright © David Montgomery and contributors',
    },
  },
})
